services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_ADDR=redis:6379
    volumes:
      - ./server/.env:/app/.env
    depends_on:
      - redis
    networks:
      - appnet
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
